### ISSUE TITLE
Modrinth is even better

### ISSUE THREAD

**Issue by GhostIsBeHere** [woodiertexas/modrinth-vs-curseforge#5]
The following lines are inaccurate

> There is no support for resource packs, MC worlds, and datapacks yet
There is also no support for Bukkit/Spigot/Paper plugins
While a good selection of mods, it has a small amount of mods (Roughly 2k-ish)
Not very well known among users

There is now support for resourcepacks and plugins, there are significantly more mods, and it is much more well known. Please make corrections accordingly

**Comment by woodiertexas** [comment]
Sorry about being late but this was dealt with in https://github.com/woodiertexas/modrinth-vs-curseforge/commit/2c1be2bb780a7df68dd527643fcab28e8cd6383c.
